# -*- coding: utf-8 -*-
"""Notebook_01_Turkish_ABSA_mBERT_EN_updated_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyfyparfDzX3OX7kzpujuZyQ1F2ID7M_

# Turkish ABSA (SemEval-style) – mBERT Fine-tuning

This notebook fine-tunes **mBERT** for Turkish restaurant **aspect-based sentiment analysis (ABSA)** using a SemEval-style dataset.

## Updates included
- Fixed the model output directory name to avoid overwriting other experiments.
- Removed the accidental extra line in the dataset section.
- Replaced the manual `"[ASPECT] ... [SEP] ..."` text formatting with **pair encoding**:
  - `aspect` as the first sequence
  - `sentence` as the second sequence
- Added stronger experiment reproducibility with fixed seeds.
- Kept both **validation** and **test** evaluation sections.
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Create the model output folder on Drive immediately
# so training can save checkpoints there in real time
OUTPUT_DIR = '/content/drive/MyDrive/bitirme_calismasi/absa_mbert_model'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Verify Drive is writable
_test = os.path.join(OUTPUT_DIR, '_write_test.txt')
with open(_test, 'w') as _f:
    _f.write('ok')
os.remove(_test)
print('Drive output folder ready:', OUTPUT_DIR)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install -U transformers datasets accelerate evaluate scikit-learn lxml

import os
import re
import random
from pathlib import Path
from typing import List, Dict

import numpy as np
import torch
from sklearn.metrics import classification_report

from datasets import Dataset, DatasetDict, ClassLabel
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
)

SEED = 42

def set_all_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_all_seeds(SEED)
print("Seed set to:", SEED)

"""## 1. Data acquisition (GitHub)"""

# Directory used for downloaded data and saved artifacts
DATA_DIR = Path('/mnt/data')
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Default GitHub repository providing SemEval-style Turkish ABSA TXT files.
GITHUB_RAW_BASE = 'https://raw.githubusercontent.com/alierkan/Turkish-ABSA/master'
TRAIN_URL = f"{GITHUB_RAW_BASE}/restaurant-train.txt"
TEST_URL  = f"{GITHUB_RAW_BASE}/restaurant-test.txt"

TRAIN_TXT = DATA_DIR / 'restaurant-train.txt'
TEST_TXT  = DATA_DIR / 'restaurant-test.txt'

def download_if_missing(url: str, path: Path):
    if path.exists() and path.stat().st_size > 0:
        return
    cmd = f"curl -L --fail -o '{path}' '{url}'"
    ret = os.system(cmd)
    if ret != 0 or (not path.exists()) or path.stat().st_size == 0:
        raise RuntimeError(f"Failed to download {url}. Please verify the URL or provide an alternative.")

download_if_missing(TRAIN_URL, TRAIN_TXT)
download_if_missing(TEST_URL, TEST_TXT)

print('Downloaded:', TRAIN_TXT, 'bytes=', TRAIN_TXT.stat().st_size)
print('Downloaded:', TEST_TXT,  'bytes=', TEST_TXT.stat().st_size)

"""## 2. Data parsing (SemEval-style TXT)"""

POLARITIES = {'negative': 0, 'neutral': 1, 'positive': 2}
ID2LABEL = {v: k for k, v in POLARITIES.items()}

# Slightly more flexible than a strict uppercase-only regex.
label_pat = re.compile(r'(negative|neutral|positive)--([^-]+)--([^-]+)--(.+)$')

def parse_turkish_absa_txt(path: str) -> List[Dict]:
    rows = []
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split('###')
            if len(parts) < 3:
                continue

            prefix = parts[0].strip()      # reviewId:sentIdx
            sentence = parts[1].strip()
            tail = '###'.join(parts[2:]).strip()

            label_chunks = [p.strip() for p in tail.split('###') if p.strip()]

            for chunk in label_chunks:
                tokens = [t.strip() for t in chunk.split() if '--' in t]
                if not tokens and '--' in chunk:
                    tokens = [chunk.strip()]

                for t in tokens:
                    m = label_pat.match(t)
                    if not m:
                        continue

                    pol, entity, aspect, target = m.group(1), m.group(2), m.group(3), m.group(4)
                    aspect_cat = f'{entity}--{aspect}'

                    rows.append({
                        'id': prefix,
                        'sentence': sentence,
                        'aspect': aspect_cat,
                        'polarity': pol,
                        'label': POLARITIES[pol],
                        'target': target,
                    })
    return rows

train_rows = parse_turkish_absa_txt(TRAIN_TXT)
test_rows = parse_turkish_absa_txt(TEST_TXT) if TEST_TXT.exists() else []

print('Train rows:', len(train_rows))
print('Test rows :', len(test_rows))
print('Example   :', train_rows[0] if train_rows else None)

from collections import Counter

print('Top aspects:', Counter([r['aspect'] for r in train_rows]).most_common(10))
print('Polarities :', Counter([r['polarity'] for r in train_rows]))

"""## 3. Dataset construction

Instead of creating a single text like:

`[ASPECT] FOOD--QUALITY [SEP] sentence`

we keep:
- `aspect`
- `sentence`

and let the tokenizer encode them as a **sequence pair**. This is cleaner and more aligned with BERT input handling.

"""

def build_hf_dataset(rows: List[Dict]) -> Dataset:
    return Dataset.from_list(
        [
            {
                'sentence': r['sentence'],
                'aspect': r['aspect'],
                'label': int(r['label']),
                'polarity': r['polarity'],
                'id': r['id'],
                'target': r['target'],
            }
            for r in rows
        ]
    )

full_train_ds = build_hf_dataset(train_rows)
test_ds = build_hf_dataset(test_rows) if test_rows else None

label_names = [ID2LABEL[i] for i in sorted(ID2LABEL.keys())]
label_features = ClassLabel(num_classes=len(POLARITIES), names=label_names)

full_train_ds = full_train_ds.cast_column('label', label_features)
if test_ds is not None:
    test_ds = test_ds.cast_column('label', label_features)

split = full_train_ds.train_test_split(
    test_size=0.15,
    seed=SEED,
    stratify_by_column='label'
)

ds = DatasetDict({
    'train': split['train'],
    'valid': split['test'],
})

if test_ds is not None:
    ds['test'] = test_ds

ds

"""## 4. Model selection and tokenization"""

MODEL_NAME = 'bert-base-multilingual-cased'  # mBERT

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize(batch):
    return tokenizer(
        batch['aspect'],
        batch['sentence'],
        truncation=True,
        max_length=256
    )

tokenized = ds.map(tokenize, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(POLARITIES),
    id2label=ID2LABEL,
    label2id=POLARITIES,
)

tokenized

import evaluate

accuracy = evaluate.load('accuracy')
f1 = evaluate.load('f1')

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    acc = accuracy.compute(predictions=preds, references=labels)
    f1_macro = f1.compute(predictions=preds, references=labels, average='macro')
    f1_weighted = f1.compute(predictions=preds, references=labels, average='weighted')

    return {
        'accuracy': acc['accuracy'],
        'f1_macro': f1_macro['f1'],
        'f1_weighted': f1_weighted['f1'],
    }

"""## 5. Fine-tuning"""

args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy='epoch',
    save_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model='f1_macro',
    greater_is_better=True,
    logging_steps=50,
    seed=SEED,
    fp16=False,
    report_to=[],
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized['train'],
    eval_dataset=tokenized['valid'],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

"""## 6. Validation evaluation"""

valid_output = trainer.predict(tokenized['valid'])
valid_preds = np.argmax(valid_output.predictions, axis=-1)
valid_labels = valid_output.label_ids

valid_metrics = compute_metrics((valid_output.predictions, valid_labels))

print("Validation metrics:")
print(valid_metrics)

print("\nValidation classification report:")
print(classification_report(valid_labels, valid_preds, target_names=label_names))

"""## 7. Test evaluation"""

if 'test' in tokenized:
    test_output = trainer.predict(tokenized['test'])

    test_preds = np.argmax(test_output.predictions, axis=-1)
    test_labels = test_output.label_ids

    test_metrics = compute_metrics((test_output.predictions, test_labels))

    print("Test metrics:")
    print(test_metrics)

    print("\nTest classification report:")
    print(classification_report(test_labels, test_preds, target_names=label_names))
else:
    print('No test set provided.')

"""## 9. Dataset Distribution Analysis

Let's analyze the distribution of sentiment labels across the training, validation, and test splits.
"""

from collections import Counter
import pandas as pd

def get_label_distribution(dataset, split_name, id2label_map):
    labels = [id2label_map[label_id] for label_id in dataset['label']]
    counts = Counter(labels)
    return {f'{split_name}_{label}': count for label, count in counts.items()}

print("Sentiment Label Distribution Across Splits:")

data_for_df = []

# Get distribution for train split
train_dist = get_label_distribution(tokenized['train'], 'train', ID2LABEL)
data_for_df.append(train_dist)
print(f"Train Split: {train_dist}")

# Get distribution for valid split
valid_dist = get_label_distribution(tokenized['valid'], 'valid', ID2LABEL)
data_for_df.append(valid_dist)
print(f"Validation Split: {valid_dist}")

# Get distribution for test split (if it exists)
if 'test' in tokenized:
    test_dist = get_label_distribution(tokenized['test'], 'test', ID2LABEL)
    data_for_df.append(test_dist)
    print(f"Test Split: {test_dist}")

# Create a DataFrame for better visualization
df_distribution = pd.DataFrame(data_for_df)
df_distribution = df_distribution.transpose().rename(columns={0: 'Count'})
df_distribution.index.name = 'Split_Label'

display(df_distribution)

"""## 8. Artifact persistence"""

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print('Saved to:', OUTPUT_DIR)

"""## Conclusion

The mBERT model has now been prepared as a cleaner and more reproducible baseline for Turkish restaurant ABSA.

### What was improved in this version
- Safer model saving path: `absa_mbert_model`
- Better reproducibility with fixed seeds
- Cleaner BERT input formatting via sequence-pair tokenization
- Validation and test evaluation preserved
"""

import os
from pathlib import Path

# Check 1: Is Drive actually mounted?
print('Drive mounted:', os.path.exists('/content/drive/MyDrive'))

# Check 2: Can we write to Drive at all?
test_file = Path('/content/drive/MyDrive/bitirme_calismasi/test_write.txt')
try:
    test_file.write_text('test')
    print('Write test: SUCCESS')
    test_file.unlink()
except Exception as e:
    print('Write test FAILED:', e)

# Check 3: What is actually in the project folder?
project = Path('/content/drive/MyDrive/bitirme_calismasi')
print(f'\nContents of {project}:')
for item in project.iterdir():
    size = ''
    if item.is_file():
        size = f'  —  {item.stat().st_size/1e6:.1f} MB'
    print(f'  {item.name}{size}')

# Check 4: Does the model folder exist and what is inside?
model_dir = project / 'absa_mbert_model'
print(f'\nModel folder exists: {model_dir.exists()}')
if model_dir.exists():
    for item in model_dir.iterdir():
        size = item.stat().st_size/1e6 if item.is_file() else 0
        print(f'  {item.name}  —  {size:.1f} MB')