# -*- coding: utf-8 -*-
"""Notebook_02_Reviews_Cleaning_EDA_EN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0Vu7KjlTicPUNTLbIh7x4s9FIBqdbTt

# Notebook 02 — Google Maps Reviews: Data Cleaning & Exploratory Data Analysis (EDA)

## Objective
This notebook prepares raw Google Maps reviews collected via Apify for downstream NLP tasks.
It focuses on schema validation, cleaning/normalization, descriptive statistics, and exporting a cleaned dataset
that will be used for sentence segmentation and dish linking.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install -U pandas pyarrow langdetect matplotlib

from google.colab import drive
drive.mount('/content/drive')

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
import matplotlib.pyplot as plt
from langdetect import detect, DetectorFactory

DetectorFactory.seed = 42

from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/restaurant_project")

RAW_PATH = DATA_DIR / "dataset_Google-Maps-Reviews-Scraper.json"
assert RAW_PATH.exists(), f"Raw dataset not found: {RAW_PATH}"

RAW_PATH

"""## 1. Load the raw dataset

The Apify export is typically either a JSON array (`[...]`) or JSON Lines (one JSON object per line).
The loader below supports both formats.

"""

def load_json_or_jsonl(path: Path) -> List[Dict[str, Any]]:
    text = path.read_text(encoding='utf-8', errors='ignore').strip()
    if not text:
        return []
    if text[0] == '[':  # JSON array
        data = json.loads(text)
        if isinstance(data, list):
            return data
        raise ValueError('Expected a JSON array.')
    # JSONL
    rows: List[Dict[str, Any]] = []
    with path.open('r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows

raw_rows = load_json_or_jsonl(RAW_PATH)
len(raw_rows), type(raw_rows[0])

df = pd.DataFrame(raw_rows)
df.head(3)

"""## 2. Schema sanity check

Key fields used by the project:
- `title`: restaurant name
- `url`: Google Maps listing URL
- `stars`: rating (1–5)
- `text`: review text
- `reviewUrl`: direct review URL (optional)

"""

expected = ['title', 'url', 'stars', 'text', 'reviewUrl']
present = [c for c in expected if c in df.columns]
missing = [c for c in expected if c not in df.columns]
print('Present:', present)
print('Missing:', missing)
print('\nAll columns:', list(df.columns))

"""## 3. Coverage statistics

This section reports:
- total records,
- number of restaurants,
- missing-text ratio,
- rating distribution.

"""

total = len(df)
n_restaurants = df['title'].nunique() if 'title' in df.columns else None
null_text_ratio = df['text'].isna().mean() if 'text' in df.columns else None

print(f'Total records: {total:,}')
print(f'Unique restaurants: {n_restaurants:,}' if n_restaurants is not None else 'Unique restaurants: N/A')
print(f'Missing text ratio: {null_text_ratio:.2%}' if null_text_ratio is not None else 'Missing text ratio: N/A')

if 'stars' in df.columns:
    print('\nStars distribution (counts):')
    print(df['stars'].value_counts(dropna=False).sort_index())

if 'stars' in df.columns:
    ax = df['stars'].value_counts().sort_index().plot(kind='bar')
    ax.set_title('Rating distribution (stars)')
    ax.set_xlabel('Stars')
    ax.set_ylabel('Count')
    plt.show()

"""## 4. Text cleaning and normalization

The cleaning procedure is conservative:
- strip whitespace,
- remove URLs,
- collapse repeated whitespace.

Rows with null/empty text are removed, as they cannot contribute to NLP tasks.

"""

url_re = re.compile(r'https?://\S+|www\.\S+', flags=re.IGNORECASE)
ws_re = re.compile(r'\s+')

def clean_text(x: Any) -> Optional[str]:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return None
    s = str(x).strip()
    if not s:
        return None
    s = url_re.sub(' ', s)
    s = ws_re.sub(' ', s).strip()
    return s if s else None

df['text_clean'] = df['text'].apply(clean_text) if 'text' in df.columns else None

before = len(df)
df_clean = df[df['text_clean'].notna()].copy() if 'text' in df.columns else df.copy()
after = len(df_clean)
print(f'Removed rows with null/empty text: {before-after:,} (kept {after:,})')

"""## 5. Duplicate removal

Duplicates can occur across scraping runs. We remove duplicates using:
- `reviewUrl` when available; otherwise
- a fallback key built from (`title`, `stars`, `text_clean`).

"""

def deduplicate_reviews(d: pd.DataFrame) -> pd.DataFrame:
    d = d.copy()
    if 'reviewUrl' in d.columns and d['reviewUrl'].notna().any():
        before = len(d)
        d = d.drop_duplicates(subset=['reviewUrl'])
        print(f'Deduplicated by reviewUrl: removed {before-len(d):,}')
        return d
    before = len(d)
    d['_dedup_key'] = (
        d.get('title', '').astype(str) + '||' +
        d.get('stars', '').astype(str) + '||' +
        d['text_clean'].astype(str)
    )
    d = d.drop_duplicates(subset=['_dedup_key']).drop(columns=['_dedup_key'])
    print(f'Deduplicated by fallback key: removed {before-len(d):,}')
    return d

df_clean = deduplicate_reviews(df_clean)
len(df_clean)

"""## 6. Text length analysis

Length statistics (characters, words) help quantify how informative the dataset is.

"""

df_clean['n_chars'] = df_clean['text_clean'].str.len()
df_clean['n_words'] = df_clean['text_clean'].str.split().apply(len)

df_clean[['n_chars','n_words']].describe(percentiles=[0.5,0.75,0.9,0.95]).T

ax = df_clean['n_words'].clip(upper=200).plot(kind='hist', bins=50)
ax.set_title('Review length distribution (words; clipped at 200)')
ax.set_xlabel('Number of words')
ax.set_ylabel('Count')
plt.show()

"""## 7. Restaurant coverage

The dish-level recommendation setting benefits from balanced review counts across restaurants.

"""

if 'title' in df_clean.columns:
    counts = df_clean['title'].value_counts()
    print(counts.head(20))
    ax = counts.head(20).plot(kind='bar')
    ax.set_title('Top restaurants by usable reviews (top 20)')
    ax.set_xlabel('Restaurant')
    ax.set_ylabel('Usable review count')
    plt.xticks(rotation=75, ha='right')
    plt.tight_layout()
    plt.show()
else:
    print('Column `title` not found; restaurant-level stats unavailable.')

"""## 8. Language detection (optional)

Language detection is applied only to reviews with at least 10 characters to reduce noise.

"""

def safe_detect_lang(text: str) -> str:
    try:
        return detect(text)
    except Exception:
        return 'unknown'

df_clean['lang'] = df_clean['text_clean'].apply(lambda s: safe_detect_lang(s) if len(s) >= 10 else 'unknown')
df_clean['lang'].value_counts().head(20)

"""## 9. Export cleaned dataset

The cleaned dataset is exported to Parquet (efficient) and CSV (portable).

"""

OUT_PARQUET = DATA_DIR / 'reviews_clean.parquet'
OUT_CSV = DATA_DIR / 'reviews_clean.csv'

cols = []
for c in ['title','url','stars','name','reviewUrl','text','text_clean','lang','n_chars','n_words']:
    if c in df_clean.columns:
        cols.append(c)

df_out = df_clean[cols].copy()
df_out.to_parquet(OUT_PARQUET, index=False)
df_out.to_csv(OUT_CSV, index=False)

print('Saved:', OUT_PARQUET)
print('Saved:', OUT_CSV)
df_out.head(3)

"""## 10. Next step

The next notebook will load restaurant menus (gazetteers), segment reviews into sentences,
link sentences to dishes (exact + fuzzy matching), and produce a dish-sentence dataset for manual labeling.

"""