# -*- coding: utf-8 -*-
"""Notebook_03_Sentence_Splitting_Dish_Linking_EN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DV4yQIc0B6iou9HHvXw-0SOy1Vg5eYfr

# Notebook 3 – Sentence Splitting + Dish Linking

## Objective
This notebook converts the cleaned restaurant review dataset from **review level** into **sentence–dish level** records.

## Inputs
1. `reviews_clean.parquet` or `reviews_clean.csv` from Notebook 2
2. **Five menu files** (one menu per restaurant)

## Main Tasks
1. Load cleaned reviews
2. Load restaurant menus
3. Normalize dish names
4. Split reviews into sentences
5. Match dishes inside sentences using:
   - exact match
   - alias match
   - fuzzy match
6. Reduce false matches using a light sentiment cue filter
7. Export the final `sentence-dish` dataset

## Output
A final dataset such as:

- `dish_sentence_pairs.parquet`
- `dish_sentence_pairs.csv`

This output will be used later for dish-level sentiment inference.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install rapidfuzz pyarrow tqdm openpyxl

from google.colab import drive
drive.mount('/content/drive')

import re
from pathlib import Path
from collections import defaultdict

import pandas as pd
from rapidfuzz import fuzz
from tqdm.auto import tqdm

pd.set_option("display.max_colwidth", 200)

"""## 1. Configure paths

Update these paths if needed.

### Expected structure example
```text
/content/drive/MyDrive/restaurant_project/
├── reviews_clean.parquet
├── reviews_clean.csv
└── menus/
    ├── restaurant_1_menu.csv
    ├── restaurant_2_menu.csv
    ├── restaurant_3_menu.csv
    ├── restaurant_4_menu.csv
    └── restaurant_5_menu.csv
```

Each menu file should contain at least:
- `restaurant_name`
- `dish_name`

If your column names are different, you can adjust them in the menu-loading section below.

"""

# Example Google Colab paths
PROJECT_DIR = Path("/content/drive/MyDrive/bitirme_calismasi")
REVIEWS_PARQUET = PROJECT_DIR / "reviews_clean.parquet"
REVIEWS_CSV = PROJECT_DIR / "reviews_clean.csv"
MENUS_DIR = PROJECT_DIR / "menus"
OUTPUT_DIR = PROJECT_DIR / "notebook3_outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_DIR:", PROJECT_DIR)
print("MENUS_DIR:", MENUS_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

"""## 2. Load cleaned reviews dataset

The notebook first tries to load `reviews_clean.parquet`.
If not found, it falls back to `reviews_clean.csv`.

"""

def load_reviews_dataset(parquet_path: Path, csv_path: Path) -> pd.DataFrame:
    if parquet_path.exists():
        print(f"Loading parquet: {parquet_path}")
        return pd.read_parquet(parquet_path)
    if csv_path.exists():
        print(f"Loading csv: {csv_path}")
        return pd.read_csv(csv_path)
    raise FileNotFoundError("Could not find reviews_clean.parquet or reviews_clean.csv")

reviews_df = load_reviews_dataset(REVIEWS_PARQUET, REVIEWS_CSV)
print("Shape:", reviews_df.shape)
reviews_df.head(3)

import os

print(f"Contents of {PROJECT_DIR}:")
for item in os.listdir(PROJECT_DIR):
    print(f"- {item}")

print(f"\nContents of {MENUS_DIR}:")
if MENUS_DIR.exists():
    for item in os.listdir(MENUS_DIR):
        print(f"- {item}")
else:
    print(f"Directory not found: {MENUS_DIR}")

"""## 3. Inspect and standardize important review columns

This cell tries to detect common column names automatically.
If your dataset uses different names, edit the mapping below.

"""

def pick_first_existing(df: pd.DataFrame, candidates, required=True):
    for c in candidates:
        if c in df.columns:
            return c
    if required:
        raise KeyError(f"None of these columns were found: {candidates}")
    return None

review_text_col = pick_first_existing(reviews_df, ["text_clean", "clean_text", "text", "review_text"])
restaurant_col  = pick_first_existing(reviews_df, ["title", "restaurant_name", "restaurant", "name"])
stars_col       = pick_first_existing(reviews_df, ["stars", "rating"], required=False)
review_url_col  = pick_first_existing(reviews_df, ["reviewUrl", "review_url", "url"], required=False)

print("review_text_col =", review_text_col)
print("restaurant_col  =", restaurant_col)
print("stars_col       =", stars_col)
print("review_url_col  =", review_url_col)

"""## 4. Load the five menu files

Place the five menu files inside the `menus/` folder.

Supported file extensions:
- `.csv`
- `.xlsx`
- `.parquet`

Each file should ideally include:
- `restaurant_name`
- `dish_name`

If a file does not contain `restaurant_name`, the notebook will try to infer the restaurant name from the file name.

"""

def load_single_menu_file(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    if suffix == ".parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported menu file type: {path}")

menu_files = sorted([p for p in MENUS_DIR.iterdir() if p.suffix.lower() in [".csv", ".xlsx", ".xls", ".parquet"]])
print("Found menu files:", len(menu_files))
for p in menu_files:
    print("-", p.name)

assert len(menu_files) > 0, f"No menu files found in {MENUS_DIR}"

menu_frames = []

for path in menu_files:
    df = load_single_menu_file(path).copy()
    df.columns = [str(c).strip() for c in df.columns]

    dish_col = None
    for c in ["dish_name", "dish", "item", "menu_item", "name"]:
        if c in df.columns:
            dish_col = c
            break
    if dish_col is None:
        raise KeyError(f"No dish column found in {path.name}. Expected one of: dish_name, dish, item, menu_item, name")

    if "restaurant_name" not in df.columns:
        inferred = path.stem.replace("_menu", "").replace("-", " ").replace("_", " ").strip()
        df["restaurant_name"] = inferred

    df = df.rename(columns={dish_col: "dish_name"})
    df = df[["restaurant_name", "dish_name"]].copy()
    df["menu_file"] = path.name
    menu_frames.append(df)

menus_df = pd.concat(menu_frames, ignore_index=True)

print("Menus shape:", menus_df.shape)
menus_df.head(10)

"""## 5. Normalize restaurant names and dish names

We create normalized versions for matching:
- lowercase
- remove extra spaces
- remove repeated punctuation
- keep a canonical dish form for later export

"""

def normalize_text(text: str) -> str:
    if pd.isna(text):
        return ""
    text = str(text).strip().lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"[_|]+", " ", text)
    text = re.sub(r"\s*/\s*", " ", text)
    text = re.sub(r"[^\w\s\-']", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

DISH_MODIFIER_STOPWORDS = {
    "large", "small", "medium", "big", "regular",
    "spicy", "hot", "extra", "special", "classic",
    "plate", "sandwich", "wrap", "combo", "meal",
    "double", "single", "with", "and", "set"
}

def canonicalize_dish_name(text: str) -> str:
    text = normalize_text(text)
    tokens = [t for t in text.split() if t not in DISH_MODIFIER_STOPWORDS]
    return " ".join(tokens).strip()

menus_df["restaurant_name_norm"] = menus_df["restaurant_name"].map(normalize_text)
menus_df["dish_name_norm"] = menus_df["dish_name"].map(normalize_text)
menus_df["dish_canonical"] = menus_df["dish_name"].map(canonicalize_dish_name)

menus_df = menus_df.dropna(subset=["dish_name"])
menus_df = menus_df[menus_df["dish_name_norm"] != ""].drop_duplicates()

menus_df.head(10)

"""## 6. Optional alias dictionary

This dictionary helps map frequent spelling variants and common surface forms to a canonical dish.

Add more aliases whenever you discover new real examples in your dataset.

"""

ALIASES = {
    "kebab": ["kebap", "kebabı", "kebabını", "kebablar"],
    "köfte": ["kofte", "koftesi", "köftesi"],
    "cağ kebab": ["cag kebab", "cağ kebabı", "cağ kebap"],
    "lahmacun": ["lahmacunu", "lahmacunlar"],
    "iskender": ["iskender kebab", "iskender kebabı"],
    "künefe": ["kunefe", "künefesi"],
    "pirzola": ["pirzolası", "pirzolalar"],
    "külbastı": ["kulbasti", "külbastısı"],
    "noodles": ["noodle", "erişte", "makarna"],
    "sweet and sour chicken": ["ekşi tatlı tavuk", "ekşi tavuk", "tatlı ekşi tavuk"],
    "rice": ["pilav", "pirinç"],
    "chicken dishes": ["tavuk", "tavuklu"],
}
ALIASES_NORM = {
    canonicalize_dish_name(k): [normalize_text(v) for v in vals]
    for k, vals in ALIASES.items()
}
ALIASES_NORM

"""## 7. Create restaurant-specific dish inventory

This allows us to match only against dishes that belong to the same restaurant.
That is much safer than using a global list for every sentence.

"""

restaurant_to_dishes = defaultdict(list)

for _, row in menus_df.iterrows():
    key = row["restaurant_name_norm"]
    restaurant_to_dishes[key].append({
        "dish_name": row["dish_name"],
        "dish_name_norm": row["dish_name_norm"],
        "dish_canonical": row["dish_canonical"],
        "menu_file": row["menu_file"],
    })

print("Number of restaurants in menus:", len(restaurant_to_dishes))
for k, v in list(restaurant_to_dishes.items())[:3]:
    print("\nRestaurant:", k)
    print("Sample dishes:", v[:5])

"""## 8. Split reviews into sentences

This is a lightweight sentence splitter based on punctuation.
It is simple but works reasonably well for noisy review text.

"""

SENTENCE_SPLIT_PATTERN = re.compile(r"(?<=[.!?؟])\s+|\n+")

def split_into_sentences(text: str):
    if pd.isna(text):
        return []
    text = str(text).strip()
    if not text:
        return []
    parts = re.split(SENTENCE_SPLIT_PATTERN, text)
    parts = [p.strip(" -•\t\r\n") for p in parts if p and p.strip(" -•\t\r\n")]
    return parts

demo_text = "The shawarma was amazing. The fries were cold! Service was fast."
split_into_sentences(demo_text)

"""## 9. Expand reviews into sentence-level rows"""

sentence_rows = []

for idx, row in tqdm(reviews_df.iterrows(), total=len(reviews_df)):
    restaurant_name = row[restaurant_col]
    review_text = row[review_text_col]

    if pd.isna(review_text) or str(review_text).strip() == "":
        continue

    sentences = split_into_sentences(review_text)

    for sent_idx, sentence in enumerate(sentences):
        sentence_rows.append({
            "review_row_id": idx,
            "restaurant_name": restaurant_name,
            "restaurant_name_norm": normalize_text(restaurant_name),
            "review_text": review_text,
            "sentence_id_in_review": sent_idx,
            "sentence": sentence,
            "sentence_norm": normalize_text(sentence),
            "stars": row[stars_col] if stars_col else None,
            "review_url": row[review_url_col] if review_url_col else None,
        })

sentences_df = pd.DataFrame(sentence_rows)
print("Sentence-level shape:", sentences_df.shape)
sentences_df.head(10)

"""## 10. Define a light sentiment cue filter

This filter helps reduce false dish links.
A sentence should not only mention a dish; it should also contain some opinion/sentiment signal.

This is only a heuristic, not a full sentiment model.
You can expand this list over time.

"""

SENTIMENT_CUES = {
    # English
    "good", "great", "amazing", "excellent", "nice", "tasty", "delicious", "perfect",
    "bad", "terrible", "awful", "poor", "dry", "cold", "bland", "overpriced",
    "fresh", "juicy", "crispy", "salty", "sweet", "spicy", "love", "loved",
    "hate", "hated", "best", "worst", "yummy", "flavorful",
    # Turkish positive
    "güzel", "harika", "lezzetli", "nefis", "muhteşem", "mükemmel", "süper",
    "iyi", "enfes", "taze", "başarılı", "tavsiye", "şahane", "fevkalade",
    # Turkish negative
    "kötü", "berbat", "rezalet", "soğuk", "tatsız", "fena", "vasat",
    "pahalı", "beğenmedim", "pişman", "hayal kırıklığı", "olmaz",
    # Turkish neutral/opinion words
    "güzeldi", "iyiydi", "lezzetliydi", "beğendim", "sevdim", "yedim",
    "öneririm", "tavsiye ederim", "tekrar", "mütiş"
}
def has_sentiment_cue(sentence_norm: str) -> bool:
    tokens = set(sentence_norm.split())
    return len(tokens.intersection(SENTIMENT_CUES)) > 0

sentences_df["has_sentiment_cue"] = sentences_df["sentence_norm"].map(has_sentiment_cue)
sentences_df["has_sentiment_cue"].value_counts(dropna=False)

"""## 11. Exact + alias + fuzzy dish matching

Matching logic:
1. **Exact match** against restaurant menu dishes
2. **Alias match**
3. **Fuzzy match** against the sentence tokens / n-grams

Only restaurant-specific dishes are considered.

"""

def token_ngrams(tokens, min_n=1, max_n=4):
    grams = []
    n_tokens = len(tokens)
    for n in range(min_n, min(max_n, n_tokens) + 1):
        for i in range(n_tokens - n + 1):
            grams.append(" ".join(tokens[i:i+n]))
    return grams

def exact_or_alias_match(sentence_norm: str, dishes_for_restaurant):
    matches = []
    for dish in dishes_for_restaurant:
        dish_norm = dish["dish_name_norm"]
        canonical = dish["dish_canonical"]

        if dish_norm and dish_norm in sentence_norm:
            matches.append({
                "matched_phrase": dish_norm,
                "dish_name": dish["dish_name"],
                "dish_canonical": canonical,
                "match_type": "exact",
                "match_score": 100
            })
            continue

        for can_dish, aliases in ALIASES_NORM.items():
            if canonicalize_dish_name(dish["dish_name"]) == can_dish:
                for alias in aliases:
                    if alias and alias in sentence_norm:
                        matches.append({
                            "matched_phrase": alias,
                            "dish_name": dish["dish_name"],
                            "dish_canonical": canonical,
                            "match_type": "alias",
                            "match_score": 100
                        })
                        break
    return matches

def fuzzy_match(sentence_norm: str, dishes_for_restaurant, threshold=90):
    matches = []
    tokens = sentence_norm.split()
    grams = token_ngrams(tokens, min_n=1, max_n=4)

    for dish in dishes_for_restaurant:
        dish_target = dish["dish_name_norm"]
        if not dish_target:
            continue

        best_score = -1
        best_phrase = None

        for gram in grams:
            score = fuzz.ratio(gram, dish_target)
            if score > best_score:
                best_score = score
                best_phrase = gram

        if best_score >= threshold:
            matches.append({
                "matched_phrase": best_phrase,
                "dish_name": dish["dish_name"],
                "dish_canonical": dish["dish_canonical"],
                "match_type": "fuzzy",
                "match_score": best_score
            })

    return matches

def deduplicate_matches(match_list):
    seen = set()
    deduped = []
    for m in match_list:
        key = (m["dish_canonical"], m["match_type"], m["matched_phrase"])
        if key not in seen:
            deduped.append(m)
            seen.add(key)
    return deduped

"""## 12. Run sentence-to-dish linking

By default:
- exact + alias matching are always used
- fuzzy matching is used only if exact/alias finds nothing

You can relax or tighten this behavior later.

"""

linked_rows = []

for _, row in tqdm(sentences_df.iterrows(), total=len(sentences_df)):
    restaurant_norm = row["restaurant_name_norm"]
    dishes_for_restaurant = restaurant_to_dishes.get(restaurant_norm, [])

    if not dishes_for_restaurant:
        continue

    sentence_norm = row["sentence_norm"]

    matches = exact_or_alias_match(sentence_norm, dishes_for_restaurant)

    if not matches:
        matches = fuzzy_match(sentence_norm, dishes_for_restaurant, threshold=90)

    matches = deduplicate_matches(matches)

    for m in matches:
        linked_rows.append({
            "review_row_id": row["review_row_id"],
            "restaurant_name": row["restaurant_name"],
            "review_url": row["review_url"],
            "stars": row["stars"],
            "sentence_id_in_review": row["sentence_id_in_review"],
            "sentence": row["sentence"],
            "sentence_norm": row["sentence_norm"],
            "has_sentiment_cue": row["has_sentiment_cue"],
            "matched_phrase": m["matched_phrase"],
            "dish_name_from_menu": m["dish_name"],
            "dish_canonical": m["dish_canonical"],
            "match_type": m["match_type"],
            "match_score": m["match_score"],
        })

linked_df = pd.DataFrame(linked_rows)
print("Linked rows shape:", linked_df.shape)
linked_df.head(20)

"""## 13. Filter weak/non-opinion links

This step keeps only rows that have a sentiment cue.
It reduces false linking such as:
- “I saw shawarma on the menu”
- “They also sell burgers”

You can later compare results with and without this filter.

"""

linked_df_before_filter = linked_df.copy()

linked_df = linked_df[linked_df["has_sentiment_cue"] == True].copy()
linked_df = linked_df.drop_duplicates(
    subset=["restaurant_name", "review_url", "sentence", "dish_canonical", "match_type", "matched_phrase"]
).reset_index(drop=True)

print("Before filter:", linked_df_before_filter.shape)
print("After  filter:", linked_df.shape)
linked_df.head(20)

"""## 14. Quick EDA on the linked sentence-dish dataset"""

print("Unique restaurants:", linked_df["restaurant_name"].nunique() if not linked_df.empty else 0)
print("Unique canonical dishes:", linked_df["dish_canonical"].nunique() if not linked_df.empty else 0)

if not linked_df.empty:
    print("\nMatch type distribution:")
    print(linked_df["match_type"].value_counts())

    print("\nTop dishes:")
    display(linked_df["dish_canonical"].value_counts().head(20).to_frame("mentions"))

    print("\nTop restaurants by linked rows:")
    display(linked_df["restaurant_name"].value_counts().head(10).to_frame("linked_rows"))

"""## 15. Inspect random samples manually

Manual inspection is very important in this notebook.
You should always sample rows and verify whether the dish linking is correct.

"""

if not linked_df.empty:
    display(linked_df.sample(min(20, len(linked_df)), random_state=42))
else:
    print("No linked rows found yet.")

"""## 16. Save final outputs

These files will be used later in the sentiment inference notebook.

"""

pairs_parquet = OUTPUT_DIR / "dish_sentence_pairs.parquet"
pairs_csv = OUTPUT_DIR / "dish_sentence_pairs.csv"

linked_df.to_parquet(pairs_parquet, index=False)
linked_df.to_csv(pairs_csv, index=False, encoding="utf-8-sig")

print("Saved parquet:", pairs_parquet)
print("Saved csv    :", pairs_csv)

print(linked_df.groupby(['restaurant_name', 'dish_canonical'])['sentence'].count().to_string())

"""## 17. Conclusion

This notebook produced a **sentence–dish level dataset** by:
- splitting reviews into sentences,
- linking sentences to restaurant menu dishes,
- using exact / alias / fuzzy matching,
- applying a light opinion filter.

The exported dataset is now ready for the next stage:
**dish-level sentiment inference and aggregation**.

"""