# -*- coding: utf-8 -*-
"""Notebook_04_Sentiment_Inference_Dish_Ranking_EN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_nq4cry5SiUkKEGWGQ9uznNZpgPlqk8

# Notebook 04 — Sentiment Inference & Dish Ranking

## Objective
This notebook runs the trained ABSA sentiment model on every `(dish, sentence)` pair
produced by Notebook 3, aggregates the results per dish per restaurant,
and produces a final ranked list of dishes.

## Inputs
1. `dish_sentence_pairs.parquet` (or `.csv`) — output of Notebook 3
2. A trained ABSA model saved in `absa_mbert_model/` or `absa_berturk_model/`

## Main Tasks
1. Load the dish-sentence pairs dataset
2. Load the trained model and tokenizer
3. Run inference — predict sentiment probabilities for each pair
4. Convert probabilities to a sentiment score
5. Aggregate scores per (restaurant, dish)
6. Rank dishes using a confidence-weighted formula
7. Flag low-confidence dishes (Java Restaurant and dishes with < 20 mentions)
8. Export results
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install transformers torch pyarrow pandas tqdm

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')

import math
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification

pd.set_option('display.max_colwidth', 120)
pd.set_option('display.float_format', '{:.4f}'.format)

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device:', DEVICE)

"""## 1. Configure paths

Update `PROJECT_DIR` and `MODEL_DIR` to match your Google Drive structure.

```text
bitirme_calismasi/
├── notebook3_outputs/
│   ├── dish_sentence_pairs.parquet
│   └── dish_sentence_pairs.csv
├── absa_mbert_model/        ← trained mBERT model
│   ├── config.json
│   ├── pytorch_model.bin
│   └── tokenizer files
└── notebook4_outputs/       ← created automatically
```

If you trained BERTurk instead, set `MODEL_DIR` to `absa_berturk_model/`.

"""

PROJECT_DIR  = Path('/content/drive/MyDrive/bitirme_calismasi')

PAIRS_PARQUET = PROJECT_DIR / 'notebook3_outputs' / 'dish_sentence_pairs.parquet'
PAIRS_CSV     = PROJECT_DIR / 'notebook3_outputs' / 'dish_sentence_pairs.csv'

# Change to 'absa_berturk_model' if you want to use BERTurk
MODEL_DIR    = PROJECT_DIR / 'absa_mbert_model'

OUTPUT_DIR   = PROJECT_DIR / 'notebook4_outputs'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print('PROJECT_DIR :', PROJECT_DIR)
print('MODEL_DIR   :', MODEL_DIR)
print('OUTPUT_DIR  :', OUTPUT_DIR)
print('Model exists:', MODEL_DIR.exists())

"""## 2. Load the dish-sentence pairs dataset

"""

if PAIRS_PARQUET.exists():
    print(f'Loading parquet: {PAIRS_PARQUET}')
    pairs_df = pd.read_parquet(PAIRS_PARQUET)
elif PAIRS_CSV.exists():
    print(f'Loading csv: {PAIRS_CSV}')
    pairs_df = pd.read_csv(PAIRS_CSV)
else:
    raise FileNotFoundError('Could not find dish_sentence_pairs.parquet or .csv')

print('Shape:', pairs_df.shape)
print('Columns:', pairs_df.columns.tolist())
pairs_df.head(3)

"""## 3. Exclude Java Restaurant

Java Restaurant has fewer than 30 dish-sentence pairs in total.
This is insufficient for reliable sentiment aggregation due to:
- Language fragmentation (Turkish / English / Indonesian / Arabic)
- Inconsistent dish naming across reviews

Java is excluded from ranking and kept separately as a case study
demonstrating data insufficiency — a documented limitation of the system.

"""

java_df  = pairs_df[pairs_df['restaurant_name'] == 'Java Restaurant'].copy()
pairs_df = pairs_df[pairs_df['restaurant_name'] != 'Java Restaurant'].copy().reset_index(drop=True)

print(f'Excluded Java Restaurant: {len(java_df)} rows')
print(f'Remaining pairs for inference: {len(pairs_df)} rows')
print()
print('Restaurants in dataset:')
print(pairs_df['restaurant_name'].value_counts())

"""## 4. Load the trained model and tokenizer

"""

import shutil
from pathlib import Path

# Step 1: Copy from Drive to local Colab storage
DRIVE_MODEL = Path('/content/drive/MyDrive/bitirme_calismasi/absa_mbert_model')
LOCAL_MODEL  = Path('/content/absa_mbert_model')

if not LOCAL_MODEL.exists():
    print('Copying model from Drive to local...')
    shutil.copytree(str(DRIVE_MODEL), str(LOCAL_MODEL))
    print('Done.')
else:
    print('Already exists locally.')

print('Files:', list(LOCAL_MODEL.iterdir()))

from pathlib import Path
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_DIR = Path('/content/drive/MyDrive/bitirme_calismasi/absa_mbert_model')

tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR, local_files_only=True)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, local_files_only=True)

print('Model loaded successfully')
print('Label mapping:', model.config.id2label)

print(f'Loading model from: {MODEL_DIR}')

# Adjust MODEL_DIR to point to the actual checkpoint folder that contains the model files
# Assuming 'checkpoint-372' is the latest/final checkpoint.
MODEL_DIR_CHECKPOINT = MODEL_DIR / 'checkpoint-372'

tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR_CHECKPOINT)
model     = AutoModelForSequenceClassification.from_pretrained(str(MODEL_DIR_CHECKPOINT))
model     = model.to(DEVICE)
model.eval()

# Verify label mapping
print('Label mapping (id -> label):', model.config.id2label)

# Expected: {0: 'negative', 1: 'neutral', 2: 'positive'}
# If the order is different in your model, update LABEL_ORDER below
LABEL_ORDER = model.config.id2label  # {0: ..., 1: ..., 2: ...}
print('Model loaded successfully.')

"""## 5. Inference — predict sentiment probabilities

For each `(dish, sentence)` pair we feed the model with:
- **Token A**: `dish_canonical` (the aspect)
- **Token B**: `sentence` (the review sentence)

This matches the pair-input format used during training in Notebook 1.

We use batch inference for speed.

"""

BATCH_SIZE  = 32
MAX_LENGTH  = 256

def predict_batch(aspects, sentences):
    """Run inference on a batch. Returns softmax probabilities as numpy array."""
    encoding = tokenizer(
        aspects,
        sentences,
        truncation=True,
        max_length=MAX_LENGTH,
        padding=True,
        return_tensors='pt'
    )
    encoding = {k: v.to(DEVICE) for k, v in encoding.items()}

    with torch.no_grad():
        logits = model(**encoding).logits

    probs = torch.softmax(logits, dim=-1).cpu().numpy()
    return probs


all_probs = []

aspects   = pairs_df['dish_canonical'].tolist()
sentences = pairs_df['sentence'].tolist()

for start in tqdm(range(0, len(aspects), BATCH_SIZE), desc='Inference'):
    end          = min(start + BATCH_SIZE, len(aspects))
    batch_probs  = predict_batch(aspects[start:end], sentences[start:end])
    all_probs.append(batch_probs)

all_probs = np.vstack(all_probs)
print(f'Inference complete. Shape of probabilities: {all_probs.shape}')

"""## 6. Attach probabilities to the dataframe

"""

# Map column index to label name using model's id2label
label_cols = {idx: label.lower() for idx, label in LABEL_ORDER.items()}

for idx, label in label_cols.items():
    pairs_df[f'prob_{label}'] = all_probs[:, idx]

# Predicted label (argmax)
pairs_df['pred_label'] = [
    label_cols[int(np.argmax(row))] for row in all_probs
]

# Sentiment score: P(positive) - P(negative)
pairs_df['sentiment_score'] = pairs_df['prob_positive'] - pairs_df['prob_negative']

print('Label distribution (predicted):')
print(pairs_df['pred_label'].value_counts())
print()
pairs_df[['sentence', 'dish_canonical', 'prob_positive', 'prob_neutral',
           'prob_negative', 'pred_label', 'sentiment_score']].head(10)

"""## 7. Spot-check — manual review of predictions

Always manually inspect a sample before trusting the aggregated scores.

"""

print('=== Sample POSITIVE predictions ===')
display(
    pairs_df[pairs_df['pred_label'] == 'positive']
    [['restaurant_name', 'dish_canonical', 'sentence', 'sentiment_score']]
    .sample(min(5, (pairs_df['pred_label'] == 'positive').sum()), random_state=42)
)

print('\n=== Sample NEGATIVE predictions ===')
display(
    pairs_df[pairs_df['pred_label'] == 'negative']
    [['restaurant_name', 'dish_canonical', 'sentence', 'sentiment_score']]
    .sample(min(5, (pairs_df['pred_label'] == 'negative').sum()), random_state=42)
)

"""## 8. Aggregate sentiment scores per (restaurant, dish)

For each (restaurant, dish) pair we compute:
- `mentions`        — number of matched sentences
- `sentiment_avg`   — mean sentiment score across all sentences
- `positive_ratio`  — fraction of sentences predicted positive
- `negative_ratio`  — fraction of sentences predicted negative
- `stars_avg`       — average star rating of reviews containing this dish

"""

agg = pairs_df.groupby(['restaurant_name', 'dish_canonical']).agg(
    mentions       = ('sentiment_score', 'count'),
    sentiment_avg  = ('sentiment_score', 'mean'),
    prob_pos_avg   = ('prob_positive', 'mean'),
    prob_neg_avg   = ('prob_negative', 'mean'),
    prob_neu_avg   = ('prob_neutral', 'mean'),
    positive_ratio = ('pred_label', lambda x: (x == 'positive').mean()),
    negative_ratio = ('pred_label', lambda x: (x == 'negative').mean()),
    neutral_ratio  = ('pred_label', lambda x: (x == 'neutral').mean()),
    stars_avg      = ('stars', 'mean'),
).reset_index()

print('Aggregated shape:', agg.shape)
agg.head(10)

"""## 9. Compute the final ranking score

We use a confidence-weighted formula:

```
final_score = sentiment_avg × sqrt(mentions)
```

**Why sqrt(mentions)?**
- A dish with `sentiment_avg = 0.9` from only 2 sentences is less reliable
  than one with `sentiment_avg = 0.8` from 100 sentences.
- `sqrt` gives diminishing returns so that a dish with 400 mentions
  is not 20× more trusted than one with 1 — just 20× the square root.

**Confidence flag:**
Dishes with fewer than 20 mentions are flagged as low-confidence.
Their scores are still shown but should not drive decisions.

"""

MIN_MENTIONS_THRESHOLD = 20

agg['final_score']      = agg['sentiment_avg'] * np.sqrt(agg['mentions'])
agg['low_confidence']   = agg['mentions'] < MIN_MENTIONS_THRESHOLD

# Rank within each restaurant (highest final_score = rank 1)
agg['rank_in_restaurant'] = (
    agg.groupby('restaurant_name')['final_score']
    .rank(method='dense', ascending=False)
    .astype(int)
)

# Global rank across all dishes and restaurants
agg['global_rank'] = (
    agg['final_score']
    .rank(method='dense', ascending=False)
    .astype(int)
)

agg = agg.sort_values(['restaurant_name', 'rank_in_restaurant']).reset_index(drop=True)

print(f'Dishes with low confidence (< {MIN_MENTIONS_THRESHOLD} mentions):')
print(agg[agg['low_confidence']][['restaurant_name', 'dish_canonical', 'mentions']].to_string(index=False))

"""## 10. Final ranked table

"""

display_cols = [
    'global_rank', 'restaurant_name', 'dish_canonical',
    'mentions', 'sentiment_avg', 'positive_ratio', 'negative_ratio',
    'final_score', 'stars_avg', 'low_confidence', 'rank_in_restaurant'
]

ranked = agg[display_cols].sort_values('global_rank')
display(ranked)

"""## 11. Per-restaurant ranking

Show the top dishes for each restaurant separately.

"""

for restaurant in sorted(agg['restaurant_name'].unique()):
    sub = agg[agg['restaurant_name'] == restaurant].sort_values('rank_in_restaurant')
    print(f'\n{'='*60}')
    print(f'  {restaurant}')
    print(f'{'='*60}')
    display(
        sub[['rank_in_restaurant', 'dish_canonical', 'mentions',
             'sentiment_avg', 'positive_ratio', 'final_score', 'low_confidence']]
        .reset_index(drop=True)
    )

"""## 12. Sentiment distribution per dish (visualization)

"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# Only plot dishes with enough mentions
plot_df = agg[~agg['low_confidence']].sort_values('final_score', ascending=False).head(20)

labels   = plot_df['dish_canonical'] + '\n(' + plot_df['restaurant_name'].str.split().str[0] + ')'
pos      = plot_df['positive_ratio'].values
neu      = plot_df['neutral_ratio'].values
neg      = plot_df['negative_ratio'].values
x        = range(len(labels))

fig, ax = plt.subplots(figsize=(14, 6))
ax.bar(x, pos, label='Positive', color='#2ecc71')
ax.bar(x, neu, bottom=pos, label='Neutral', color='#95a5a6')
ax.bar(x, neg, bottom=pos + neu, label='Negative', color='#e74c3c')

ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=9)
ax.set_ylabel('Proportion of sentences')
ax.set_title('Sentiment distribution per dish (top 20 by final score, ≥20 mentions)')
ax.legend(loc='upper right')
ax.set_ylim(0, 1)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'sentiment_distribution.png', dpi=150)
plt.show()

"""## 13. Final score bar chart

"""

plot_df2 = agg[~agg['low_confidence']].sort_values('final_score', ascending=True).tail(20)

labels2 = plot_df2['dish_canonical'] + ' (' + plot_df2['restaurant_name'].str.split().str[0] + ')'
colors  = ['#2ecc71' if s >= 0 else '#e74c3c' for s in plot_df2['final_score']]

fig, ax = plt.subplots(figsize=(10, 8))
bars = ax.barh(labels2, plot_df2['final_score'], color=colors)
ax.axvline(0, color='black', linewidth=0.8)
ax.set_xlabel('Final score  (sentiment_avg × √mentions)')
ax.set_title('Top dishes by final score (≥20 mentions)')
plt.tight_layout()
plt.savefig(OUTPUT_DIR / 'final_score_ranking.png', dpi=150)
plt.show()

"""## 14. Save all outputs

"""

# Full predictions (all pairs with probabilities)
preds_parquet = OUTPUT_DIR / 'predictions.parquet'
preds_csv     = OUTPUT_DIR / 'predictions.csv'
pairs_df.to_parquet(preds_parquet, index=False)
pairs_df.to_csv(preds_csv, index=False, encoding='utf-8-sig')
print('Saved predictions:', preds_parquet)

# Aggregated scores and ranking
agg_parquet = OUTPUT_DIR / 'dish_scores.parquet'
agg_csv     = OUTPUT_DIR / 'dish_scores.csv'
agg.to_parquet(agg_parquet, index=False)
agg.to_csv(agg_csv, index=False, encoding='utf-8-sig')
print('Saved dish scores:', agg_parquet)

# Java Restaurant kept separately for documentation
java_csv = OUTPUT_DIR / 'java_excluded.csv'
java_df.to_csv(java_csv, index=False, encoding='utf-8-sig')
print('Saved Java (excluded):', java_csv)

"""## 15. Java Restaurant — case study note

Java Restaurant is intentionally excluded from the ranking.
It serves as a documented example of a restaurant where the system
cannot produce reliable results due to:

1. **Language fragmentation** — reviews in Turkish, English, Indonesian, Arabic
2. **Inconsistent dish naming** — the same dish appears as `tatlı ekşi tavuk`,
   `ekşi tatlı tavuk`, `tatlı acı tavuk` — never settling on one form
3. **Low review volume after filtering** — only ~30 dish-sentence pairs
   out of 187 total reviews

This finding is included in the thesis as evidence that:
> *The system's effectiveness is contingent on review volume,
> language consistency, and menu-review language alignment.
> Restaurants with fragmented or low-volume review data
> should be flagged rather than ranked.*

"""

print('Java Restaurant — dish-sentence pair counts:')
print(java_df['dish_canonical'].value_counts().to_string())
print(f'\nTotal Java pairs: {len(java_df)}')
print('Status: EXCLUDED — insufficient data for reliable ranking')

"""## 16. Conclusion

This notebook produced:

- `predictions.parquet` — every (dish, sentence) pair with sentiment probabilities
- `dish_scores.parquet` — aggregated scores and ranking per (restaurant, dish)
- `sentiment_distribution.png` — stacked bar chart of sentiment ratios
- `final_score_ranking.png` — horizontal bar chart of final scores
- `java_excluded.csv` — Java Restaurant pairs kept as a case study

The dish scores are now ready to be loaded into the web application (ASP.NET)
and used to answer user queries such as:
- *"Where can I find good kebap?"*
- *"How is the köfte at GÜRKAN ET?"*

"""

import os
from pathlib import Path

# Check 1: Is Drive actually mounted?
print('Drive mounted:', os.path.exists('/content/drive/MyDrive'))

# Check 2: Can we write to Drive at all?
test_file = Path('/content/drive/MyDrive/bitirme_calismasi/test_write.txt')
try:
    test_file.write_text('test')
    print('Write test: SUCCESS')
    test_file.unlink()
except Exception as e:
    print('Write test FAILED:', e)

# Check 3: What is actually in the project folder?
project = Path('/content/drive/MyDrive/bitirme_calismasi')
print(f'\nContents of {project}:')
for item in project.iterdir():
    size = ''
    if item.is_file():
        size = f'  —  {item.stat().st_size/1e6:.1f} MB'
    print(f'  {item.name}{size}')

# Check 4: Does the model folder exist and what is inside?
model_dir = project / 'absa_mbert_model'
print(f'\nModel folder exists: {model_dir.exists()}')
if model_dir.exists():
    for item in model_dir.iterdir():
        size = item.stat().st_size/1e6 if item.is_file() else 0
        print(f'  {item.name}  —  {size:.1f} MB')